language: node_js

node_js:
  - "5"
  - "4"

cache:
  directories:
    - node_modules

addons:
  firefox: "latest"
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_install:
  - npm install -g npm@latest

script:
  - npm test

after_success:
  - test $TRAVIS_BRANCH = "master" && npm run sca $GALAXY_URL
  - npm install codeclimate-test-reporter -g
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f32378437048df440f25
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
